config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  get "home/index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: :dashboard
  end

  root "home#index"
  resources :users do
    resources :tasks
  end
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :description, presence: true
    validates :due_date, presence: true
    enum status: { pending: 'pending', in_progress: 'in_progress', complete: 'complete'}

    scope :for_user, -> (user) { where(user:user) }
    scope :for_admin, -> { all }

    def self.fetch_tasks(user, selected_user = nil)
        return for_user(user) unless user.admin?
        selected_user ? for_user(selected_user) : for_admin

    end
end

app/controllers/task_controller.rb
# class TasksController < ApplicationController
#     before_action :authenticate_user!  
#     before_action :set_task, only: [:show, :edit, :update, :destroy]


#   def index
#     @tasks = current_user.tasks
#   end
  
#     def new
#       @task = current_user.tasks.build  
#     end
  
#     def create
#       @task = current_user.tasks.build(task_params)  
#       if @task.save
#         redirect_to user_task_path(current_user, @task), notice: 'Task was successfully created.'
#       else
#         render :new
#       end
#     end
  
#     def edit
#     end
  
#     def update
#       if @task.update(task_params)
#         redirect_to @task, notice: 'Task was successfully updated.'
#       else
#         render :edit
#       end
#     end
  
#     def show
#     end
  
#     def destroy
#       @task.destroy
#       redirect_to tasks_path, notice: 'Task has been deleted.'
#     end
  
#     private
  
#     def set_task
#       @task = current_user.tasks.find(params[:id])
#     end
  
#     def task_params
#       params.require(:task).permit(:title, :description, :due_date, :status)
#     end
#   end
  
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def index
      @tasks = current_user.tasks
    end
  
    def new
      @task = current_user.tasks.build
    end
  
    def create
      @task = current_user.tasks.build(task_params)
      if @task.save
        redirect_to user_task_path(current_user, @task), notice: 'Task was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @task.update(task_params)
        redirect_to user_task_path(current_user, @task), notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end
  
    def show
    end
  
    def destroy
      @task.destroy
      redirect_to user_tasks_path(current_user), notice: 'Task has been deleted.'
    end
  
    private
  
    def set_task
      @task = current_user.tasks.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :status)
    end
  end
  

app/controllers/tasks_controller.rb
 
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :create]

def index
  @tasks = Task.fetch_tasks(current_user, @user)
end


  def new
    @task = Task.new
    render 'form'  
  end

 
  
def create
  @task = Task.new(task_params)
  if @task.save
    redirect_to user_tasks_path(@task.user), notice: "Task was successfully created."
    else
      render "form"
    end
  end

  def edit
    render 'form'  
  end

   def update
    if @task.update(task_params)
      redirect_to user_tasks_path(@task.user), notice: "Task was successfully updated."
    else
      render "form"
    end
  end

  def show
  end

  def destroy
    @task.destroy
    redirect_to user_tasks_path(current_user), notice: 'Task has been deleted.'
  end

  private

def set_task
  @task = Task.find_by(id:params[:id])
  unless @task && (current_user.admin? || @task.user == current_user)
    redirect_to tasks_path, alert: "You are not authorized to view this task."
  end
end


def set_user
  @user = User.find(params[:user_id]) if params[:user_id]

end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :status, :user_id)
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<div class="form_fields">
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :due_date %><br>
    <%= form.date_field :due_date %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Task.statuses.keys.map { |status| [status.humanize, status] }, selected: @task.status || "pending" %>
  </p>
  <p>
  <%= form.label :user_id, "Assign To" %> <br>
  <%= form.collection_select :user_id, User.all, :id, :email, include_blank: true %>
    </p>
</div>

<div class="submit">
  <p>
    <%= form.submit @task.new_record? ? 
    "Create Task" : "Update Task" %>
  </p>
</div>

app/views/tasks/form.html.erb


<h2><%=@task.new_record? ? "Create a task:" : "Edit task:" %></h2>
<div class="form">
<%= form_with model: [current_user, @task] do |form| %>
<%= render partial: 'form', locals: {form: form} %>
<% end %> 
</div>

app/views/tasks/index.html.erb
<head>
<%= stylesheet_link_tag "tasks", media: "all", "data-turbo-track": "reload" %>
</head>
<h1>Tasks List from views-tasks-index </h1>
<div class="tasks">

<div class="new_task" >
<%= link_to 'New Task', new_user_task_path(current_user) %>
</div>
</div>
<div class="task_view">
<ul>
  <% @tasks.each do |task| %>
    <li>
      <strong>Title:</strong> <%= task.title %><br>
      <strong>Description:</strong> <%= task.description %><br>
      <strong>Due Date:</strong> <%= task.due_date %><br>
      <strong>Status:</strong> <%= task.status.present? ? task.status.humanize : "unknown" %><br>
    
      <div class="edit-delete-button">
        <%= link_to 'Edit', edit_user_task_path(current_user, task) %>
      </div>
      <div class="edit-delete-button">
        <%= button_to 'Delete', user_task_path(current_user, task), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure you want to delete this task?' } %>
      </div>
    </li>
  <% end %>
</ul>
</div>

app/views/tasks/show.html.erb
<head>
  <%= stylesheet_link_tag "show_task", media: "all", "data-turbo-track": "reload" %>
</head>

<div class="details">
  <h1><%= @task.title %></h1>

  <p><strong>Description: </strong> <%= @task.description %></p>
  <p><strong>Due Date: </strong> <%= @task.due_date %></p>
  <p><strong>Status: </strong> <%= @task.status.present? ? @task.status.humanize : "unknown" %></p>
</div>

<div class="crud-actions">
  <div class="crud">
    <%= link_to "Edit", edit_user_task_path(current_user, @task), class: 'crud-link' %>
  </div>
  
  <div class="crud">
    <%= button_to 'Delete', user_task_path(@task), method: :delete, class: 'crud-link', data: { confirm: "Do you want to Delete" } %>
  </div>
  
  <div class="crud">
    <%= link_to "Back", user_tasks_path(current_user), class: 'crud-link' %>
  </div>
</div>