config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  get "home/index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: :dashboard
  end

  root "home#index"
  resources :users do
    resources :tasks
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  
  def index
    @users = User.all
    @tasks = Task.includes(:user).all
end

def check_if_admin
    redirect_to root_path, alert: "You are not authorized to view this content." unless current_user.admin?
end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>

<h2>All Users</h2>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'View Tasks', user_tasks_path(user) %>
          <td>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<h2>All Tasks</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Assigned To</th>
      <th>Actions</th>
      <th>Reassign</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.user.email if task.user %></td>
        
        <td>
          <%= form_with model: task, url: user_task_path(task.user, task), method: :patch do |form| %>
          <%= form.collection_select :user_id, User.all, :id, :email, include_blank: true %>
          <%= form.submit "Reassign" %>
          <% end %>
        </td>
        <td>
        <%= button_to 'Delete', user_task_path(task.user, task), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure you want to delete this task?' } %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>